Traceback (most recent call last):
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/alexandra/Library/Python/3.8/lib/python/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
employee = ("Jane", "Doe", 31, "Software Developer")

employee[0] = "John"
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-b12d1c27d9d5>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0memployee[0m [0;34m=[0m [0;34m([0m[0;34m"Jane"[0m[0;34m,[0m [0;34m"Doe"[0m[0;34m,[0m [0;36m31[0m[0;34m,[0m [0;34m"Software Developer"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0memployee[0m[0;34m[[0m[0;36m0[0m[0;34m][0m [0;34m=[0m [0;34m"John"[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: 'tuple' object does not support item assignment
TypeError: 'tuple' object does not support item assignment

